### PR TITLE
chore: Add tox<4.0.0 to constraints.txt

### PR DESCRIPTION
**Pull request by ZiqiXiao**
Run make upgrade with Python 3.8. 
https://github.com/openedx/public-engineering/issues/217

Reviewer
- [ ]  @feanil

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ZiqiXiao!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by feanil — APPROVED** [review]

**Comment by e0d** [comment]
@ZiqiXiao Looks like there are some test failures, can you have a look.

**Comment by mphilbrick211** [comment]
> @ZiqiXiao Looks like there are some test failures, can you have a look.

Hi @ZiqiXiao! Just following up on this.

**Comment by mphilbrick211** [comment]
Hi @ZiqiXiao! Just checking in to see if you plan on pursuing this pull request?

**Comment by ZiqiXiao** [comment]
Hi, sorry, I don’t have any time to keep up with this pull request. 


| |
肖子奇
|
|
***@***.***
|


---- Replied Message ----
| From | Michelle ***@***.***> |
| Date | 12/12/2023 04:41 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [openedx/bok-choy] chore: Add tox<4.0.0 to constraints.txt (PR #467) |

Hi @ZiqiXiao! Just checking in to see if you plan on pursuing this pull request?

**Comment by openedx-webhooks** [comment]
@ZiqiXiao Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/bok-choy&entry.867055334=https://github.com/openedx/bok-choy/pull/467&entry.1484655318=https://github.com/ZiqiXiao&entry.752974735=2023-10-26+06:14&entry.1917517419=2023-12-12+01:45&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
